name: Update Labels on Issue Move

on:
  issues:
    types:
      - moved
  project_card:
    types:
      - moved

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue moved within project board
        id: check-issue-move
        run: |
          if [[ "${{ github.event_name }}" == "project_card" && "${{ github.event.action }}" != "moved" ]]; then
            echo "No action needed. Exiting..."
            exit 0
          fi
          if [[ "${{ github.event_name }}" == "issues" && "${{ github.event.issue.moved }}" != true ]]; then
            echo "No action needed. Exiting..."
            exit 0
          fi
          echo "Issue moved within project board. Proceeding..."
        shell: bash

      - name: Get issue number
        id: get-issue-number
        run: echo "::set-output name=issue_number::${{ github.event.issue.number }}"

      - name: Update labels
        run: |
          # get issue number
          issue_number="${{ steps.get-issue-number.outputs.issue_number }}"
          #get the current labels from the issue
          current_labels=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues/${issue_number}/labels" | jq -r '.[].name')
          
          # Check to find if the issue was moved
          if [[ "${{ github.event_name }}" == "project_card" ]]; then
            #check and update for the 'in progress' column
            if [[ "${{ github.event.project_card.column_name }}" == "In Progress" ]]; then
              labels=("In Progress" "Mechanical")
            else
              labels=()
            fi
            # check and update for the 'review' column
            elif [[ "${{ github.event.project_card.column_name }}" == "Review" ]]; then
              labels=("Review" "Mechanical")
            else
              labels=()
            fi
            # check and update for the closed column, will also close the issue
            elif [[ "${{ github.event.project_card.column_name }}" == "Closed" ]]; then
              labels=("Closed" "Mechanical")
              #close the issue
              curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"state\":\"closed\"}" "https://api.github.com/repos/${{ github.repository }}/issues/${issue_number}"
            else
              labels=()
            fi
            # check for issues moved back to open and update its labels
            elif [[ "${{ github.event.project_card.column_name }}" == "Open" ]]; then
              labels=("Open" "Mechanical")
            else
              labels=()
            fi
          fi
          
          # Add or remove labels as needed
          for label in "${labels[@]}"; do
            if [[ ! "$current_labels" =~ "$label" ]]; then
              echo "Adding label: $label"
              curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"labels\": [\"$label\"]}" "https://api.github.com/repos/${{ github.repository }}/issues/${issue_number}/labels"
            fi
          done
          for label in $current_labels; do
            if [[ ! "${labels[@]}" =~ "$label" ]]; then
              echo "Removing label: $label"
              curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues/${issue_number}/labels/$label"
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
