name: Update Labels on Issue Move

on:
  project_card:
    types:
      - moved
  issues:
    types:
      - moved

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue moved within project board
        id: check-issue-move
        run: |
          if [[ "${{ github.event_name }}" == "project_card" && "${{ github.event.action }}" != "moved" ]]; then
            echo "No action needed. Exiting..."
            exit 0
          fi
          if [[ "${{ github.event_name }}" == "issues" && "${{ github.event.issue.moved }}" != true ]]; then
            echo "No action needed. Exiting..."
            exit 0
          fi
          echo "Issue moved within the Steamer Trunk Project Board. Proceeding..."
        shell: bash

      - name: Get issue number
        id: get-issue-number
        run: echo "::set-output name=issue_number::${{ github.event.issue.number }}"

      - name: Update labels
        run: |
          # Get issue number
          issue_number="${{ steps.get-issue-number.outputs.issue_number }}"
          # Get the current labels from the issue
          current_labels=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues/${issue_number}/labels" | jq -r '.[].name')

          # Check to find if the issue was moved within the Steamer Trunk Project Board
          if [[ "${{ github.event_name }}" == "project_card" ]]; then
            # Check and update for the 'In Progress' column
            if [[ "${{ github.event.project_card.project_name }}" == "Steamer Trunk Project Board" && "${{ github.event.project_card.column_name }}" == "In Progress" ]]; then
              labels=("In Progress" "Mechanical")
            # Check and update for the 'Review' column
            elif [[ "${{ github.event.project_card.project_name }}" == "Steamer Trunk Project Board" && "${{ github.event.project_card.column_name }}" == "Review" ]]; then
              labels=("Review" "Mechanical")
            # Check and update for the 'Closed' column; will also close the issue
            elif [[ "${{ github.event.project_card.project_name }}" == "Steamer Trunk Project Board" && "${{ github.event.project_card.column_name }}" == "Closed" ]]; then
              labels=("Closed" "Mechanical")
              # Close the issue
              curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"state\":\"closed\"}" "https://api.github.com/repos/${{ github.repository }}/issues/${issue_number}"
            # Check for issues moved back to 'Open' and update their labels
            elif [[ "${{ github.event.project_card.project_name }}" == "Steamer Trunk Project Board" && "${{ github.event.project_card.column_name }}" == "Open" ]]; then
              labels=("Open" "Mechanical")
            fi
          elif [[ "${{ github.event_name }}" == "issues" ]]; then
            # Check and update for the 'In Progress' column
            if [[ "${{ github.event.issue.project_name }}" == "Steamer Trunk Project Board" && "${{ github.event.issue.column_name }}" == "In Progress" ]]; then
              labels=("In Progress" "Mechanical")
            # Check and update for the 'Review' column
            elif [[ "${{ github.event.issue.project_name }}" == "Steamer Trunk Project Board" && "${{ github.event.issue.column_name }}" == "Review" ]]; then
              labels=("Review" "Mechanical")
            # Check and update for the 'Closed' column; will also close the issue
            elif [[ "${{ github.event.issue.project_name }}" == "Steamer Trunk Project Board" && "${{ github.event.issue.column_name }}" == "Closed" ]]; then
              labels=("Closed" "Mechanical")
              # Close the issue
              curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"state\":\"closed\"}" "https://api.github.com/repos/${{ github.repository }}/issues/${issue_number}"
            # Check for issues moved back to 'Open' and update their labels
            elif [[ "${{ github.event.issue.project_name }}" == "Steamer Trunk Project Board" && "${{ github.event.issue.column_name }}" == "Open" ]]; then
              labels=("Open" "Mechanical")
            fi
          fi

          # Add or remove labels as needed
          for label in "${labels[@]}"; do
            if [[ ! "$current_labels" =~ "$label" ]]; then
              echo "Adding label: $label"
              curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"labels\": [\"$label\"]}" "https://api.github.com/repos/${{ github.repository }}/issues/${issue_number}/labels"
            fi
          done
          for label in $current_labels; do
            if [[ ! "${labels[@]}" =~ "$label" ]]; then
              echo "Removing label: $label"
              curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues/${issue_number}/labels/$label"
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
